<a href="https://colab.research.google.com/github/Lathika2006/Python-Basics/blob/main/2_2_Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Programming Languages used for Machine Learning:


1.   Python
2.   R



#print function

In [ ]:
print("Machine Learning")

Machine Learning


In [ ]:
print("Machine Learning" + " Projects")

Machine Learning Projects


In [ ]:
print(8)

8


In [ ]:
print(8+3)

11


#Basic Data types:


1.   int
2.   float
3.   str





In [ ]:
type(8)

int

In [ ]:
type(5.3)

float

In [ ]:
type("english")

str

#Constants & Variables

In [ ]:
marvel_super_hero = "Iron Man"
print(marvel_super_hero)

Iron Man


In [ ]:
marvel_super_hero = "Captain America"
print(marvel_super_hero)

Captain America


In [ ]:
hero1 , hero2 , hero3 = "Iron Man" , "Captain America" , "Bat Man"
print(hero1)
print(hero2)
print(hero3)

Iron Man
Captain America
Bat Man


In [ ]:
x = y = z = 23
print(x)
print(y)
print(z)

23
23
23


# input Function

In [ ]:
number_1 = int(input("Enter the first number : "))
number_2 = int(input("Enter the second number : "))

sum = number_1 + number_2
print(sum)

Enter the first number : 23
Enter the second number : 23
46


In [ ]:
# changing the data type in python:
num = 5
print(float(num))


5.0


# Numpy

In [1]:
import numpy as np

In [2]:
from time import process_time

In [3]:
#Time taken by a list
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007644639999999647


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00021820900000002474


In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)



[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:

a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.69182931 0.35171496 0.71304473 0.88945305]
 [0.99608535 0.73411394 0.41169566 0.39961153]
 [0.02366777 0.25971857 0.28823567 0.62035822]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[38 93 23 64 87]
 [86 38 38 30 21]
 [23 83 78 94 62]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:

# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array


In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[30 18 19 30 54]
 [22 33 42 49 36]
 [86 67 61 80 69]
 [31 62 33 77 33]
 [19 72 85 63 47]]


In [24]:
# array dimension
print(c.shape)


(5, 5)


In [25]:
# number of dimensions
print(c.ndim)


2


In [26]:
# number of elements in an array
print(c.size)

25


In [27]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [30]:
print(a)
print(b)

[[9 7 2]
 [8 9 9]
 [0 1 5]]
[[11 12 16]
 [15 10 12]
 [11 17 18]]


In [31]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[20 19 18]
 [23 19 21]
 [11 18 23]]
[[ -2  -5 -14]
 [ -7  -1  -3]
 [-11 -16 -13]]
[[ 99  84  32]
 [120  90 108]
 [  0  17  90]]
[[0.81818182 0.58333333 0.125     ]
 [0.53333333 0.9        0.75      ]
 [0.         0.05882353 0.27777778]]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [33]:
print(a)
print(b)

[[6 7 9]
 [7 2 6]
 [4 0 8]]
[[13 19 11]
 [16 11 12]
 [13 16 17]]


In [34]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 26 20]
 [23 13 18]
 [17 16 25]]
[[ -7 -12  -2]
 [ -9  -9  -6]
 [ -9 -16  -9]]
[[ 78 133  99]
 [112  22  72]
 [ 52   0 136]]
[[0.46153846 0.36842105 0.81818182]
 [0.4375     0.18181818 0.5       ]
 [0.30769231 0.         0.47058824]]


Array Manipulation

In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 6 8]
 [8 7 2]]
(2, 3)


In [36]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 8]
 [6 7]
 [8 2]]
(3, 2)


In [37]:

array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[4 9 0]
 [5 5 6]]
(2, 3)


In [38]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 5]
 [9 5]
 [0 6]]
(3, 2)


In [39]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 5 3]
 [5 1 5]]
(2, 3)


In [40]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 5]
 [3 5]
 [1 5]]
(3, 2)
